### ISSUE TITLE
Add Sample Jupyter Notebook

### ISSUE THREAD

**Issue by StevenMMortimer** [NorfolkDataSci/LEMAS-analysis#2]
Add a Jupyter notebook that provides the basic outline of how to read all of the datasets and structure into a master longitudinal file. Then push this longitudinal file back to the repository for others to use. This ticket seems a duplicate of Issue #1, but the reason for having 2 formats is so that collaborators who are more comfortable in one language over the other (R or Python) can have a quick jumping off platform from both languages.

**Comment by josibake** [comment]
Notebook added. No easy way to combine individual years into master longitudinal file. You'll have to pick some variables you want to observe over time and figure out what they are called in each study (if present).
