### ISSUE TITLE
Add Header Row to Datasets

### ISSUE THREAD

**Issue by StevenMMortimer** [NorfolkDataSci/LEMAS-analysis#3]
The ASCII datasets do not have a header and there is a not a reference file other than the PDF codebook. Figure out a way to add the headers and commit in order to lower barriers to entry.

**Comment by josibake** [comment]
Tried playing around with the ASCII datasets. Is there a reason you used those instead of the TSV's? I wasn't able to get the ASCII files loaded @ReportMort

**Comment by StevenMMortimer** [comment]
@josibake The older file (I think pre-2000) are not available as TSV's, so I thought I'd grab all ASCII, then I saw the issue with the ASCII's is that it's fixed width format with no headers. It might be smart to go back and get TSV's even though we lose some longitudinal history. I'm personally conflicted at the moment.

**Comment by josibake** [comment]
@ReportMort its actually post 2000 that isn't in ASCII  👎  I'll load the tsv file sand then go back and make a separate issue for the ASCII files.

**Comment by josibake** [comment]
Looks like each dataset has a different set of column names. The SAS and STATA files have a nice mapping, but that file would have to be parsed. The STATA file looks like it could be parsed fairly easily to get column names to pass to pandas.read_fwf function. Would be useful beyond this project to have a way of reading STATA, SAS files into python (or R)

**Comment by josibake** [comment]
Added script for taking ASCII txt file with STATA setup and outputting a csv with column names.
